"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
var google_1 = require("next/font/google");
require("./globals.css");
var inter = (0, google_1.Inter)({ subsets: ['latin'] });
exports.metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en">
      <body className={inter.className}>{children}</body>
    </html>);
}
exports.default = RootLayout;
